version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: data4bt-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      CLICKHOUSE_DB: crypto
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # 可选：ClickHouse的Web UI
  clickhouse-ui:
    image: spoonest/clickhouse-tabix-web-client:latest
    container_name: data4bt-clickhouse-ui
    ports:
      - "8080:80"
    depends_on:
      - clickhouse
    restart: unless-stopped

volumes:
  clickhouse_data:
    driver: local

networks:
  default:
    name: data4bt-network