# Docker Compose 配置 - 仅用于开发环境
# 注意：此项目使用现有的共享 ClickHouse 容器 (47d30449ba3e)
# 该容器运行在端口 8123:8123 和 9000:9000
# 包含 data4trend 数据库，我们将在其中创建 data4BT 数据库

# 如果需要其他服务，可以在此添加
services: {}

# 备注：使用现有 ClickHouse 容器的连接信息
# - 地址: localhost:9000
# - 用户: default  
# - 密码: 123456
# - 现有数据库: data4trend
# - 新数据库: data4BT